baseURL = "https://gogabrielbr.github.io/blog/"
canonifyURLS = true
config = "config.toml"
disableKinds = ["taxonomy", "taxonomyTerm"]
disqusShortname = "gogabrielbrasil"
googleAnalytics = ""
languageCode = "en-US"
publishDir = "docs"
tags = ["portfolio", "technology", "blog"]
theme = "osprey"
title = "Gabriel Brasil"
[[menu.main]]
name = "ITP"
url = "pages/itp"
weight = 4
[[menu.main]]
name = "Contact"
url = "/#contact"
weight = 4
[[menu.main]]
name = "Blog"
url = "/#blog"
weight = 3
[[menu.main]]
name = "Work"
url = "/#work"
weight = 2
[[menu.main]]
name = "About"
url = "/#about"
weight = 1
[params]
ajaxformspree = true
author = "Gabriel Brasil"
cachebustcss = false
cachebustjs = false
copyright = true
credit = true
customcss = true
description = "Designer and Graduate Student at NYU - Interactive Telecommunications Program"
email = "gmg384@nyu.edu"
favicon = "favicon.ico"
github = "gogabrielbr"
googletagmanger = ""
highlightjs = true
linkedin = "tomanistor"
logobig = "/images/ejectnow.gif"
logosmall = "/images/ejectnow-banner-03.png"
opengraphimage = "/images/ejectnow-banner-03.png"
tagline = "Eject Now"
twitter = "gabrasil"
