title = "Gabriel Brasil"
baseURL = "https://gogabrielbr.github.io/blog/"
tags = ["portfolio", "technology", "blog"]
languageCode = "en-US"
config = "config.toml"
theme = "osprey"
canonifyURLS = true
googleAnalytics = ""
disqusShortname = "gogabrielbrasil"
disableKinds = ["taxonomy", "taxonomyTerm"] # This theme does not currently use "tag" and "category" taxonomies
#GABRIEL Changes default from "public" to  githubs "docs" folder
publishDir = "docs"

[Params]
    tagline = "Gabriel Brasil"
    author = "Gabriel Brasil"
    description = "Designer and Graduate Student at NYU - Interactive Telecommunications Program"
    logoBig = "/images/ejectnow.gif"
    logoSmall = "/images/ejectnow-banner-03.png"
    favicon = "favicon.ico"
    opengraphImage = "/images/ejectnow-banner-03.png"
    twitter = "TomaNistor"
    linkedin = "tomanistor"
    github = "gogabrielbr"
    email = "gmg384@nyu.edu"
    googleTagManger = ""
    highlightJS = true
    copyright = true
    credit = true
    customCSS = true
    cacheBustCSS = false
    cacheBustJS = false
    ajaxFormspree = true

[[menu.main]]
    name = "About"
    url  = "/#about"
    weight = 1
[[menu.main]]
    name = "Work"
    url  = "/#work"
    weight = 2
[[menu.main]]
    name = "Blog"
    url  = "/#blog"
    weight = 3
[[menu.main]]
    name = "Contact"
    url  = "/#contact"
    weight = 4
[[menu.main]]
    name = "ITP"
    url  = "/#ITP"
    weight = 4
